pipeline {
    agent any

    environment {
      	DOCKER_REGISTRY = "http://prod:5000/v2"
        PROD_USERNAME = "user"
        PROD_IP = "2.12.100.66"
    }

    stages {



        stage("Deployment Double Vision"){
            when {
                branch 'release/doublevision*'
            }
            steps {
                script {
                    env.IMAGE_NAME = "ybs_doublevision"
                    env.NGINX_PORT = "7075"
                }
            }
        }
      
        stage("Deployment AYBS Web"){
            when {
                branch 'master'
            }
            steps {
                script {
                    env.IMAGE_NAME = "ybs_aybs_web"
                    env.NGINX_PORT = "7076"
                }
            }
        }


        stage ("Printing Environments..") {
            steps{
                echo "${BRANCH_NAME}"
                echo "${IMAGE_NAME}"
                echo "${NGINX_PORT}"
            }
        }

        stage("Push to Private Registry") {
            when {
                expression {
                    env.BRANCH_NAME.contains("release");
                }
            }
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_NAME}:${BUILD_NUMBER}", "--build-arg NGINX_PORT=${NGINX_PORT} .")
                    docker.withRegistry("${DOCKER_REGISTRY}") {
                    	dockerImage.push("$BUILD_NUMBER")
                    	dockerImage.push("latest")
                    }
                }
            }
        }

        stage("Deployment") {
            when {
                expression {
                    env.BRANCH_NAME.contains("release");
                }
            }
            steps {
                sh "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${PROD_USERNAME}@${PROD_IP} 'cd /opt/docker && docker-compose up -d --build ${IMAGE_NAME}'";
            }
        }

    }
}