pipeline {
    agent any

    environment {
      	DOCKER_REGISTRY = "http://prod:5000/v2"
        PROD_USERNAME = "svrn"
        PROD_IP = "prod"
    }

    stages {

         stage("Deployment AYBS Player"){
            when {
                branch 'master'
            }
            steps {
                script {
                    env.IMAGE_NAME = "test_aybs"
                    env.NGINX_PORT = "8079"
                }
            }
        }

        stage ("Printing Environments..") {
            steps{
                echo "${BRANCH_NAME}"
                echo "${IMAGE_NAME}"
                echo "${NGINX_PORT}"
            }
        }

        stage("Push to Private Registry") {
            when {
                expression {
                    env.BRANCH_NAME.contains("master");
                }
            }
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_NAME}:${BUILD_NUMBER}", "--build-arg NGINX_PORT=${NGINX_PORT} .")
                    docker.withRegistry("${DOCKER_REGISTRY}") {
                    	dockerImage.push("$BUILD_NUMBER")
                    	dockerImage.push("latest")
                    }
                }
            }
        }

     /*   stage("Deployment") {
            when {
                expression {
                    env.BRANCH_NAME.contains("release");
                }
            }
            steps {
                sh "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${PROD_USERNAME}@${PROD_IP} 'cd /home/svrn/eshot_mgmt && docker-compose up -d --build ${IMAGE_NAME}'";
            }
        }
	*/
    }
}